server:  
    port: 8888
    servlet: 
       session.timeout: 60000
       context-path: /yc74ibike
       application-display-name: yc74ibike
    undertow:  
        io-threads: 16  
        worker-threads: 256  
        buffer-size: 1024  
        buffers-per-region: 1024  
        direct-buffers: true 
logging:
    level:
        com:
            yc: debug
swagger: 
    enabled: true
spring:
    datasource:
        url: jdbc:mysql://liyang:3306/cnr-clouduser?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: a
        driver-class-name: com.mysql.jdbc.Driver
        #配置外部静态资源路径 文件上传的路径

